//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie
{
    using System;
    using System.Collections.Generic;
    
    public partial class compagnies_employes
    {
        public compagnies_employes()
        {
            this.jours_travailles = new HashSet<jours_travailles>();
        }
    
        public int id { get; set; }
        public System.DateTime premier_jour_emploi { get; set; }
        public int compagnie_id { get; set; }
        public int employe_id { get; set; }
    
        public virtual compagnies compagnies { get; set; }
        public virtual ICollection<jours_travailles> jours_travailles { get; set; }
        public virtual employes employes { get; set; }
    }
}
