//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie
{
    using System;
    using System.Collections.Generic;
    
    public partial class types_retenues
    {
        public types_retenues()
        {
            this.paies_retenues = new HashSet<paies_retenues>();
            this.types_retenues_employes = new HashSet<types_retenues_employes>();
        }
    
        public int id { get; set; }
        public string nom_retenue { get; set; }
        public System.DateTime en_vigueur_debut { get; set; }
        public System.DateTime en_vigueur_fin { get; set; }
        public decimal minimum { get; set; }
        public decimal plafond { get; set; }
        public sbyte part_employeur { get; set; }
        public decimal pourcentage { get; set; }
    
        public virtual ICollection<paies_retenues> paies_retenues { get; set; }
        public virtual ICollection<types_retenues_employes> types_retenues_employes { get; set; }
    }
}
