//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacances
    {
        public int id { get; set; }
        public System.DateTime date_vacance { get; set; }
        public decimal nombre_heures { get; set; }
        public int paie_id { get; set; }
        public int employe_id { get; set; }
    
        public virtual employes employes { get; set; }
        public virtual paies paies { get; set; }
    }
}
