//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie.CodeGenere
{
    using System;
    using System.Collections.Generic;
    
    public partial class compagnies
    {
        public compagnies()
        {
            this.compagnies_employes = new HashSet<compagnies_employes>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string no_rue { get; set; }
        public string ville { get; set; }
        public string code_postal { get; set; }
        public System.DateTime premier_jour_paie { get; set; }
        public int frequence_paie_j { get; set; }
        public string NEQ { get; set; }
        public string NE { get; set; }
    
        public virtual ICollection<compagnies_employes> compagnies_employes { get; set; }
    }
}
