//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie.CodeGenere
{
    using System;
    using System.Collections.Generic;
    
    public partial class employes
    {
        public employes()
        {
            this.compagnies_employes = new HashSet<compagnies_employes>();
            this.jours_travailles = new HashSet<jours_travailles>();
            this.types_retenues_employes = new HashSet<types_retenues_employes>();
            this.vacances = new HashSet<vacances>();
        }
    
        public int id { get; set; }
        public string numero_employe { get; set; }
        public string prenom { get; set; }
        public string nom { get; set; }
        public System.DateTime date_naissance { get; set; }
        public int NAS { get; set; }
        public sbyte actif { get; set; }
        public string note { get; set; }
        public string pseudonyme { get; set; }
        public string mot_de_passe { get; set; }
        public sbyte admin { get; set; }
        public string email { get; set; }
        public string no_rue { get; set; }
        public string ville { get; set; }
        public string code_postal { get; set; }
        public string telephone { get; set; }
        public decimal taux_horaire { get; set; }
        public int pourcentage_vacance { get; set; }
        public sbyte paie_vacance { get; set; }
        public string bidon { get; set; }
        public string employescol { get; set; }
    
        public virtual ICollection<compagnies_employes> compagnies_employes { get; set; }
        public virtual ICollection<jours_travailles> jours_travailles { get; set; }
        public virtual ICollection<types_retenues_employes> types_retenues_employes { get; set; }
        public virtual ICollection<vacances> vacances { get; set; }
    }
}
