//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleDePaie.CodeGenere
{
    using System;
    using System.Collections.Generic;
    
    public partial class paies_retenues
    {
        public int id { get; set; }
        public int paie_id { get; set; }
        public int type_retenue_id { get; set; }
    
        public virtual paies paies { get; set; }
        public virtual types_retenues types_retenues { get; set; }
    }
}
